apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:ksb+XGv8JDsPsQ50ljS5BJu/IGQ8xHMgGupzsrOYGsTFGFUu3Pviog==,iv:uu5gdlyJe5o3SR/Ne3lafSBA/ap5vPVjCDuWi/U1tvk=,tag:U/UZyJL0mSyC7ucBlQeaGQ==,type:str]
sops:
  age:
    - recipient: age15uspxd57sg8aqw5wnew58y7l5ywtctsazv5599g8w7245v6gpqvq7k40ay
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvMncrS1lEU1lJSTdaejBO
        dnZsRmc3SEsvbGZmQXRrcnh5NTJwcnVYbFFNCjhaWmYxa1VSWUhHSllRNFlNV2c3
        aWM5bHBKVWtFZFdNVnhFSjQ5eUVOcmcKLS0tIGE0SFkzNG8ybHNRL0dkRGx0N1VX
        ZlVkSExGZHdlY29GNmt6UTZPWm5ZVWsKtgS0ITVhgIUucHzDLKcFAg0S6Rfej3PP
        lQ9pBjnSAH21qyhwgcV6fAtmyf+DI/yXHteFaC0w1OEOaGVijpkGdQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-02T00:48:05Z"
  mac: ENC[AES256_GCM,data:7/HKiOMy7YsRRq/tNfH819GV+MifVm5575tZJWGQ0So9G0aubmaiNfUVh1nFEbXWKkGFgTFkuxgSLwAfIdJdusmpLT1ZxV6Wky5nJI/neHDn9wJtZkUx6nGSr7+Jy2yKxGk51JODiqEtfxFc0vNpmShv8xStiu+Lg6ErUcYzBy4=,iv:WnWvt0BBBoxtde0Eln9nsa5h8SJC8XwTyvqg6IG0OUc=,tag:rDa8n8g1ET/1DmQcvFmG0w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
