apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:L5WP3aLqw/4TEpdz,iv:lCrvaCCweMl2zcdjV8SJTI81Mu3zOgvvlV67DLsxKog=,tag:lhMQCe8ijrTewCThsB1s4Q==,type:str]
sops:
  age:
    - recipient: age15uspxd57sg8aqw5wnew58y7l5ywtctsazv5599g8w7245v6gpqvq7k40ay
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXMUh4ZzcxZnRQN2VEOW5p
        NmJpMTl2NEc0d3JhZC9XQ2M2MnpMMk5lMm00CjREb2pnSmQ4TlNrc2RBNlp2RTBO
        amRFNFU4NkhUZEhvcWhlR0FGS3M5VmcKLS0tIE9sWkRzQ2xEVTBkcWVUemw5YWRi
        UStCQUhpY0M3K2FUMVJXc1NTY2Z1emcKKHRaRG/lFcnA2XR4cgJWDJs2+qUeXvDN
        kT6AKzX2Nwr0TmgSGg7hZhr4lmUSAFGW5MxL0YVt5r+OV5/oyVkUmw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-02T00:48:05Z"
  mac: ENC[AES256_GCM,data:BaHW/eosWqxw6Xv7SrQG2yFw9Lw+vd5GmZkL9CvIwkZHQZoxRDbsnuZ7tme0xuWwFPj4UnXKuBmhSyTRi5mH2QRLcVD26XL5d3AcZMQpxnkpQodXX6f2pdmTmxsXZsTPTCPbchTM5FWDpG8i2mvNXLcQN8DvPBU1/ZnEldOj2Jk=,iv:dgtAHGnYc1rGIab6VRZLEtbJUBqSam+4QtWJ3zPXLPA=,tag:AJmhjEcPtka5ISqbVAejQA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
