apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:CEwg9gJVOMWWIfJ/nn7mHSY/+P78X52x5mSFjpMVNDU=,iv:SGaE2l/XfGtFKIYJmoeCKrlKebxbkqXqQX7HlKTmYGY=,tag:su0Xkskic/F9ZDrj1Yvt+w==,type:str]
sops:
  age:
    - recipient: age15uspxd57sg8aqw5wnew58y7l5ywtctsazv5599g8w7245v6gpqvq7k40ay
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYUEtVSkRQSnp0ZTVuSlhu
        Q1BOU05ONVdTSUhuaDdwcTRZNnQxUENpbjFrClJsQk15UGZJTW1FSmNXY1VIK0lB
        SVcyd1l4RkcxT3hHTENGbVBIeXkyWHcKLS0tIHdCKzNGcHBQZ2U4NFhRZFR5Qm84
        QXJkRTIrZDBlSEFsMFZZVmpOTDhOWmMKLTdPLbwzsBmpp2r5gDP9oOqyAMdV+uai
        9UD1TFj6InEzLT5Vqq8B9NlRK0kwSqnZmcGjd0uD7hGXtzkMFCXiWg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-02T00:48:05Z"
  mac: ENC[AES256_GCM,data:1dY60l+loB8DTWjEU0D4P9BALqsU+Ir1+McwmntHBKOLOXWhdkoJP6NIkdoF8r76ElMfJpzgur2V14HnNatF+Wqbzns2btjlQxJ5EVn0MhubdSOOthpKXHj9uPH08wJSywdpDVupKVk1Wu10PpkqFAe7nKS43OJAivST8imqc8w=,iv:Vl+vBOMHPV08275NaxXDP7CxDuFFj1B1et5lhMqKnsM=,tag:2Z5LuAWk6/G8HKb8Ld2xcQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
