---
# SecretProviderClass for mounting Azure Key Vault secrets via CSI driver
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-keyvault-csi
  namespace: kube-system
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "${AZURE_CLIENT_ID}"
    keyvaultName: "${AZURE_KEYVAULT_NAME}"
    cloudName: "AzurePublicCloud"
    objects: |
      array:
        - |
          objectName: age-private-key
          objectAlias: keys.txt
          objectType: secret
        - |
          objectName: github-deploy-key
          objectAlias: github-deploy.key
          objectType: secret
        - |
          objectName: github-deploy-key-pub
          objectAlias: github-deploy.key.pub
          objectType: secret
        - |
          objectName: cloudflare-tunnel
          objectAlias: tunnel.json
          objectType: secret
    tenantId: "${AZURE_TENANT_ID}"
