apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:mUuMEfkhD0zcW7bDi5E2HWhfp9eyd4OtDtL2NTG1o0XnYwL2G9lyQc1LqZxzEcydDipyNa4BHtVlitPYKiFe6A5it4ewLsZ7lk1o1dNp6S3aXeUnFBedTTN5IEDFR1uV5qQDCpK1f04jxKzr58xbX/ZSMFkkwkBgLbyAlY3L1DJVF8qSsuji8g2nXCNkTQSDxkguunzANAx+ooOdPP0NQeOQRvv7pbrOb1ysqlJfjDUHSu7m,iv:xJgKBqvRraIYHRoBu7Qndqevq2hC8SKWDHl3nlGUle8=,tag:IUkf4WPh9ZnciiM3oGMt1Q==,type:str]
sops:
  age:
    - recipient: age15uspxd57sg8aqw5wnew58y7l5ywtctsazv5599g8w7245v6gpqvq7k40ay
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNUGtBTWhYSUdOTmRqU2dW
        V2JJWnErSlJtMFBmcVJXNll0M0VWRXJBdFRnCnJpY2Vrci9sMWRRUnFBZ2V2ZXNY
        RmttdXhmMnU3K08vRmVBa0FZNTJxQUUKLS0tIG1xeUM1M2orektiUmFUYXFXcmpx
        MEVIYVNWdU5yVXM2SU43eWtva3BsNE0K9HNG9XRo7cWBnF0YWVl2Ptjb8ajKPkWT
        chxqExNZ5pdR/NFJM+/MO0+sUkd8FCzF4BTOKxKd06olAJ8NR8453Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-02T00:48:05Z"
  mac: ENC[AES256_GCM,data:r1mpSIES389L42NnqvyCnupbQouUSCQyHOiwvBcpOKpTuVdC6m0bC21+hOOKqD1b1pIWm4+i3zFPsVieM6bA379Fe8ZRjFTsYclrdK+3QaNH40/+PtEy/s/VRAXY7I/l+zyTe+c5Zl3a9Th3KMzzn97+z7n/dEDjlLavIl37Jx4=,iv:T7WdJMod21zi35Wh6WtDanCOJ/casu++cuXvoXid7Ho=,tag:ltCHMkaetU9+qgbsMMCddQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
