---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sops-age-keys
  namespace: flux-system
spec:
  refreshPolicy: OnChange
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-keyvault
  target:
    name: sops-age-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        age.agekey: "{{ .agePrivateKey }}"
  data:
    - secretKey: agePrivateKey
      remoteRef:
        key: age-private-key
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-tunnel
  namespace: network
spec:
  refreshPolicy: OnChange
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-keyvault
  target:
    name: cloudflare-tunnel-id-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        CLOUDFLARE_TUNNEL_ID: "{{ .cloudflareId }}"
  data:
    - secretKey: cloudflareId
      remoteRef:
        key: cloudflare-tunnel-id
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: github-credentials
  namespace: flux-system
spec:
  refreshPolicy: OnChange
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-keyvault
  target:
    name: github-credentials
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        username: "git"
        password: "{{ .githubToken }}"
  data:
    - secretKey: githubToken
      remoteRef:
        key: github-push-token
