apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:M33WID2ItKPL5cQfzv0/iaMZgWXcIR7DJpua5jJ7hcq0PxXShOySxw==,iv:bUti6W6QYpqO1KOa8KAL9CDJ1j1b/ZMB1K6qEY2AYNQ=,tag:H0jjFEU9y3y6Q9OnduK9Zw==,type:str]
sops:
  age:
    - recipient: age15uspxd57sg8aqw5wnew58y7l5ywtctsazv5599g8w7245v6gpqvq7k40ay
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzMy9qMGw0MWd6UitFMFFn
        TVRtN3kzMUFodm43M21kdkFHUTBHT0QyekRVCkdsWXhWREJIM3dxTlR2QzZFRXJC
        NnA3VG4wdjJobzIzWTBLc2E2QkRYUmcKLS0tIGFDb0V1MzN0Mk9sMktLRVhHem9E
        RnF3SCtCWUFpbSt4MFRFODNscys5c1EK4DiR8u8Y5dbCQCr5dEm4QE0zCSxIDAmJ
        pD3ONUpZiMPZ8uxHirJjSn5OyBQaEUCCJoszVKI16i5bHYTmj6n4Wg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-02T00:48:05Z"
  mac: ENC[AES256_GCM,data:huGoD3GMUH1kuv9jKEPVT9I1Y1BH9DH5D/bX4FuPVhjFkSIHlos2iJcu8/HU1LzBxg8bK7KTprIKwnSpo98ZcQ9V0M0jdUgLWkRgJTtw6XNzsoJygUo+7nxxERAnhay5e/czQGP0mKX66KV2niI351LRukoV81fWtfXDNSyC2kc=,iv:YMz+bVc5Qr5JXxWCqEh3IYaTu0jAWqPvhNT2R6tcrrk=,tag:US6N3ada9PE2CWUh/dyWSA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
